collections:
- product

collections:
  product:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "product" # previously `post` in Jekyll 2.2.
    values:
      layout: "product"
